D8AGE-284 Validate API
openeuropa/cdt-client pull request #6
Opened 2024-02-28 12:38 UTC by intelektron

2024-02-28 12:40 UTC, intelektron commented on src/Endpoint/EndpointBase.php
> +    protected function handleResponseException(ResponseInterface $response): void
I've added this method to be able to override it. The Validate/Requests API will use it to catch and serve 400 error.

2024-02-28 12:40 UTC, intelektron commented on src/Endpoint/EndpointBase.php
> +        if ($json = $this->getRequestJsonBody()) {
This case was not covered by the original Open Europa Search client. We simply need to send a JSON body.

2024-02-28 12:41 UTC, intelektron commented on src/Endpoint/EndpointBase.php
> +            new CustomNormalizer(),
CustomNormalizer is added to support Base64 conversion
AttributeLoader is needed to read PHP attributes with json path names

2024-02-28 12:42 UTC, intelektron commented on src/Endpoint/TokenEndpoint.php
> +    protected function getSerializer(): SerializerInterface
The serializer for the Token needs to be different, as the endpoint uses snake_case

2024-02-28 12:43 UTC, intelektron commented on src/Exception/ValidationErrorsException.php
> +class ValidationErrorsException extends \RuntimeException
This is a new type of exception, thrown when `ValidationAwareTrait` is used

2024-02-28 12:45 UTC, intelektron commented on src/Model/BaseCollection.php
> +abstract class BaseCollection extends \ArrayIterator
I created this class as a base of all class collection, it allows strict typing of all methods. Please let me know if there is a smoother way to create an iterator.

2024-02-28 12:47 UTC, intelektron commented on src/Model/Request/File.php
> +    public function normalize(NormalizerInterface $normalizer, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
This is needed to normalize the string to Base64. There may be a better way to do this, but I am not sure it is worth the time for such a small class.

2024-02-28 12:48 UTC, intelektron commented on src/Traits/ValidationAwareTrait.php
> +trait ValidationAwareTrait
This trait will be used by all endpoints that may return some validation data

2024-02-28 12:49 UTC, intelektron commented on tests/src/Endpoint/ValidateEndpointTest.php
> +                (string) file_get_contents(__DIR__ . '/../../fixtures/json/validate_valid_request.json'),
I also added verifying the request serialization, to make sure if all the serialization attributes are correct.

2024-02-28 12:51 UTC, intelektron commented on tests/src/Traits/AssertTestCollectionTrait.php
> +     * @psalm-param class-string<RealInstanceType> $class
These annotations are needed because of PHPStan issues with `class-string`

2024-02-28 12:54 UTC, intelektron commented on tests/src/Traits/AssertTestCollectionTrait.php
> +        try {
I couldn't expect the exception here, as I needed to test multiple exceptions.

2024-02-28 12:54 UTC, intelektron commented on tests/src/Traits/AssertTestCollectionTrait.php
> +trait AssertTestCollectionTrait
This trait tests each collection with 100% coverage

2024-02-28 12:54 UTC, intelektron commented on tests/src/Traits/RequestModelTestTrait.php
> +trait RequestModelTestTrait
This trait was added to make it easier to generate request data. By default, it returns proper values that pass the validation.

2024-03-01 08:56 UTC, drishu requested changes
Good quality work. Regarding commits, do make them more granular, in case we need to drop commits or cherry pick into a new branch to make the work easy.
I recommend doing development to a certain point, then using git add -p to create several commits grouping patches of code together where it makes sense

2024-03-01 08:56 UTC, drishu commented on README.md
> +    ->setComments('Do not translate the URLs')
leave only $translationRequest = new Translation();, leave only the one use statement

2024-03-01 08:56 UTC, drishu commented on README.md
> +To create the translation request, you need to build the `OpenEuropa\CdtClient\Model\Request\Translation` object:
Let's keep it simple, lets say "to validate a translation request run the following code"
then the try/catch snippet and that sentence about the return values

2024-03-01 08:56 UTC, drishu commented on src/Endpoint/EndpointBase.php
> +     * The separate method for handling exceptions, that may be changed by child classes and traits.
```suggestion
     * Handles ...
```

2024-03-01 08:56 UTC, drishu commented on src/Endpoint/EndpointBase.php
> +     * Override this method to define the body of the request as JSON.
```suggestion
     * Gets the ...
     *
     * Override this method to provide a JSON body for a request.
```
The short description should always start with the "Action" of the function name, Gets, Sets, Adds, etc
Do this for all pls and then the more detailed explanation can be the "Override.." part

2024-03-01 08:56 UTC, drishu commented on src/Model/Response/ValidationErrors.php
> +    public function getMessage(): string
Either we comment all methods in a file, or we comment only those that need a bit more context, I'd prefer the second approach

2024-03-01 08:56 UTC, drishu commented on src/Endpoint/EndpointBase.php
> +        // Simple JSON body.
please also check, but I think that all files data are handled via base64 encoding and no multipart requests are supported, I think its best if we also remove everything related to that. Even better, I think we can do that in another ticket.

2024-03-01 08:56 UTC, drishu commented on src/Model/BaseCollection.php
> +abstract class BaseCollection extends \ArrayIterator
Extending the `\ArrayObject` class provides a solid implementation of these interfaces.
As we discussed there is the issue when denormalizing somekey[{},{}]
Let's drop the collections, create a follow up ticket and go with just arrays of objects for now

2024-03-01 08:56 UTC, drishu commented on src/Model/Request/Callback.php
> +     */
Lets comment only where it is not clear/needs further context or clarification, not just here but generally

2024-03-01 08:56 UTC, drishu commented on src/Model/Request/File.php
> +    public function normalize(NormalizerInterface $normalizer, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
Its fine but I think its a much cleaner solution if we just implement the `\JsonSerializable` like so
```
public function jsonSerialize(): mixed
    {
        return [
            'fileName' => $this->fileName,
            'base64Data' => base64_encode($this->content),
        ];
    }
```
and use the JsonSerializableNormalizer instead of the CustomNormalizer

2024-03-01 08:56 UTC, drishu commented on src/Model/Request/ReferenceFile.php
> +     * @return string[]
comments like this are perfect, it adds more clarification to something that is not clear from code

2024-03-04 12:33 UTC, intelektron commented on src/Model/Response/ValidationErrors.php
> +    public function getMessage(): string
At some point I noticed that it was inconsequent from the very beginning. I rather tried to provide minimal context (like in Clean Code) and avoid the Drupal-like approach of commenting everything. I made an exception for the interface definitions. So I agree with the second approach.

We just have to talk how to apply this change, maybe it makes sense to merge everything into one branch first, and fix all files at once.

2024-03-04 12:34 UTC, intelektron commented on src/Endpoint/EndpointBase.php
> +        // Simple JSON body.
I am almost certain that we don't need requests other than pure JSON

2024-03-04 12:35 UTC, intelektron commented on src/Model/Request/File.php
> +    public function normalize(NormalizerInterface $normalizer, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
True, it looks like a much better idea

2024-03-04 13:32 UTC, intelektron commented on src/Model/BaseCollection.php
> +abstract class BaseCollection extends \ArrayIterator
Moved to D8AGE-370

2024-03-06 08:43 UTC, drishu approved these changes

2024-03-06 08:44 UTC, merged